version: 1.0.{build}
image: Visual Studio 2017

environment:

  matrix:

  - PYTHON: "C:\\Python27-x64"
  - PYTHON: "C:\\Python36-x64"
  - PYTHON: "C:\\Python37-x64"


build: off

install:
# To run Nodejs workflow integ tests
- ps: Install-Product node 8.10

- "set PATH=%PYTHON%\\Scripts;%PYTHON%\\bin;%PATH%"
- "%PYTHON%\\python.exe -m pip install -r requirements/dev.txt"
- "%PYTHON%\\python.exe -m pip install -e ."
- "$version = \"Ruby 2.5.3-1\""
- "$install_path = \"C:\Ruby25\""
- "$download_url = \"https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.3-1/rubyinstaller-2.5.3-1-x86.exe\""
- "$exePath = \"$($env:TEMP)\rubyinstaller.exe\""
- "Write-Host \"  Downloading $($version) from $($download_url)\" -ForegroundColor Gray"
- "(New-Object Net.WebClient).DownloadFile($download_url, $exePath)"
- "Write-Host \"Installing...\" -ForegroundColor Gray"
- "cmd /c start /wait $exePath /verysilent /dir=\"$($install_path.replace('\', '/'))\" /tasks=\"noassocfiles,nomodpath,noridkinstall\""
- "del $exePath"
- "Write-Host \"Installed\" -ForegroundColor Green"
- "set PATH=C:\Ruby2.5\bin;%PATH%"
- "gem install bundler"

test_script:
- "%PYTHON%\\python.exe -m pytest --cov aws_lambda_builders --cov-report term-missing tests/unit tests/functional"
- "%PYTHON%\\python.exe -m pytest tests/integration"
